#!/bin/bash

# This file is part of Marionnet, a virtual network laboratory
# Copyright (C) 2010  Jean-Vincent Loddo
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

TOP=/tmp/$(basename $0)

make marionnet.byte

# Get the correct command line for compiling marionnet.byte
# then replace "ocamlc.opt" by "ocamlmktop"
# and the target "marionnet.byte" by $TOP

CMD=$(grep 'ocamlc.opt .*-o marionnet.byte'  _build/_build/_log \
 | sed -e 's/\/usr\/bin\/ocamlc.opt/ocamlmktop -I _build/' \
 | sed -e "s/marionnet.byte/\/tmp\/$(basename $0)/" )

# Launch the toplevel creation: 
eval "$CMD"
INCLUDES=$(echo $CMD | tr ' ' '\n' | /bin/grep '^-I$' -A1 | tr '\n' ' ' \
         | sed -e 's/--//')

# Add the current _build/ directory to include directories (very important):
INCLUDES="$INCLUDES -I $PWD/_build"

export MARIONNET_DEBUG=true

# Launch the toplevel:
if   which rlwrap &>/dev/null; then rlwrap $TOP $INCLUDES "$@"
elif which ledit  &>/dev/null; then ledit $TOP $INCLUDES "$@"
else
 eval $TOP $INCLUDES "$@"
 rm -f $TOP
fi

# The executable is not removed from /tmp/ in order to reuse the history
# of commands (managed by rlwrap and ledit)
