val name : string
val version : string
val prefix : string
val ocaml_libraryprefix : string
val libraryprefix : string
val configurationprefix : string
val localeprefix : string
val documentationprefix : string
val uname : string
val build_date : string
val revision : string
val source_date : string
val source_date_utc_yy_mm_dd : string
