(* This file is part of our reusable OCaml BRICKS library
   Copyright (C) 2019  Jean-Vincent Loddo

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 2 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>. *)

(** Minimize the number of copies of structures generated by a function.
    Given a function f:('a -> 'b), we compose it with a memoized version
    of the identity id:('b -> 'b) in the obvious way λx.id (f x).
    This kind of composition, which is a memoisation acting on the codomain
    instead of the domain as usual, will be called "adhere". *)

type 'b identity = ('b -> 'b)

(* Make an hash table to detect and filter 'b copies generated by a function: *)
val adhere : ?id:'b identity -> ('a -> 'b) -> ('a -> 'b)

(* Make an hash table to detect and filter 'b copies: *)
val id : unit -> 'b identity

(* Get also the internal hash table in order to control the used memory: *)
val id_ht  : unit -> 'b identity * ('b,'b) Hashtbl.t

(* Easy interface for arrays (i.e. when the codomain is an array): *)
module Array : sig

  (* Make an hash table to detect ('b list) copies in an array container: *)
  val id : ?elt:'b identity -> unit -> ('b array) identity

  (* Just `Array.id' composed with `adhere': *)
  val adhere : ?elt:'b identity -> ('a -> 'b array) -> ('a -> 'b array)

end

(* Easy interface for lists (i.e. when the codomain is a list).
   The option ~sublists:() is really extreme! *)
module List : sig

  (* Make an hash table to detect ('b list) copies in a list container: *)
  val id : ?sublists:unit -> ?elt:'b identity -> unit -> ('b list) identity

  (* Just `List.id' composed with `adhere': *)
  val adhere : ?sublists:unit -> ?elt:'b identity -> ('a -> 'b list) -> ('a -> 'b list)

end

(* General functorized interface. The module Array defined above may be viewed as an instance
   of this functor applied to the standard module Array. Instead, the module List defined above
   is more than a simple application of this functor because of the recursive nature of the list
   exploited to enhance sharing. *)
module Through : functor (M : sig  type 'a t  val map : ('a -> 'b) -> 'a t -> 'b t  end) ->
  sig
    type 'a t = 'a M.t

    val id : ?elt:'b identity -> unit -> 'b t identity

    (* Just `id' composed with `adhere': *)
    val adhere : ?elt:'b identity -> ('a -> 'b t) -> ('a -> 'b t)

  end

(*
-------------------------------------------------
                    Example
-------------------------------------------------

let size_of x =
    let b = Bytes.length (Marshal.to_bytes x [Marshal.Closures]) in
    (`bytes b, `Kb (b/1024), `Mb (b/(1048576)))

(* val f : int -> (int list) array
   # f 4 ;;
   - : int list array = [|[0]; [1; 0]; [2; 1; 0]; [3; 2; 1; 0]|] *)
let f x = Loop.Array.init_folding ~range:x ~init:[] (fun s j -> j::s, j::s)  ;;

let f1 = Extreme_sharing.Array.adhere f ;;
let f2 = Extreme_sharing.Array.adhere ~elt:(Extreme_sharing.List.id ~sublists:() ()) f ;;

let fm,  ht  = Memo.memoize_and_get_table f ;;
let f1m, ht1 = Memo.memoize_and_get_table f1 ;;
let f2m, ht2 = Memo.memoize_and_get_table f2 ;;

let make_a_structure_with g = [| g 10; g 11; g 12; g 13; g 14; g 15; g 16; g 15; g 14; g 13; g 12; g 11; g 10 |] ;;

(make_a_structure_with f) = (make_a_structure_with f1)  &&
(make_a_structure_with f) = (make_a_structure_with f2)  &&
(make_a_structure_with f) = (make_a_structure_with fm)  &&
(make_a_structure_with f) = (make_a_structure_with f1m) &&
(make_a_structure_with f) = (make_a_structure_with f2m) ;;
(* - : bool = true *)

size_of (make_a_structure_with f) ;;
size_of (make_a_structure_with f1) ;;
size_of (make_a_structure_with f2) ;;
(* (`bytes 1034, `Kb 1, `Mb 0) *)
(* (`bytes 614,  `Kb 0, `Mb 0) *)
(* (`bytes 453,  `Kb 0, `Mb 0) *)

size_of (make_a_structure_with fm) ;;
size_of (make_a_structure_with f1m) ;;
size_of (make_a_structure_with f2m) ;;
(* (`bytes 590, `Kb 0, `Mb 0) *)
(* (`bytes 446, `Kb 0, `Mb 0) *)
(* (`bytes 285, `Kb 0, `Mb 0) *)

size_of ht;;
size_of ht1;;
size_of ht2;;
(* (`bytes 854, `Kb 0, `Mb 0) *)
(* (`bytes 710, `Kb 0, `Mb 0) *)
(* (`bytes 549, `Kb 0, `Mb 0) *)

(* ====== Slimming an hash table ====== *)

# let id = Extreme_sharing.Array.id ~elt:(Extreme_sharing.List.id ~sublists:() ()) () ;;
val id : '_a list array Extreme_sharing.identity

# let slim ht = Hashtbl.iter (fun x y -> Hashtbl.replace ht x (id y)) ht ;;
val slim : ('a, int list array) Hashtbl.t -> unit

*)
